//! Live doorbell camera (Phase 1, issues #103–#105): siphon the panel's own cleartext
//! A/V and fan it out for Home Assistant, with NO SIP and NO extra device tooling.
//!
//! ## Mechanism (firmware-verified on the Classe 100X and 300X)
//! The on-board `bt_av_media` daemon encodes the entrance camera to a GStreamer
//! `multiudpsink` (H.264 for video, speex for audio). Sending a WHO=7
//! `*7*300#<ip>#<port>#<branch>*##` frame to its command port (`:30007`) **adds a UDP
//! client** to that sink — a non-disruptive fan-out: the panel keeps rendering to its own
//! client while it *also* sends a cleartext RTP copy to the `ip:port` we name. So we
//! never decode, transcode, or open `/dev/video` here — we just ask for a copy.
//!
//! ## What this task does
//! It runs its **own** OWN monitor session (`:20000`), independent of `sender.rs`, so it
//! can't perturb the reviewed call-state machine there. Whenever the panel brings an A/V
//! session up — a ring, an answered call, or the eye/self-view — the bus carries the
//! panel's own `*7*300#127#0#0#1#<port>#<branch>*##` frames; we take that as "media is
//! live now" and **add our own client** on `:30007`, pointing the low-res H.264 (+ speex
//! audio) at `camera_target` (the go2rtc/Home-Assistant host). When the panel tears the
//! session down (`*7*0*##`) we simply drop our `:30007` connection.
//!
//! ## Why we never send `*7*0*##`
//! In this ring/self-view flow the **panel** owns the session lifecycle. `*7*0*##` tears
//! down the WHOLE media session (every `multiudpsink` client, including the panel's own
//! on-screen view). We must not do that — a resident looking at the door would lose the
//! picture. We only ever ADD a client and let the panel's own teardown remove it. (The
//! on-demand path in #104, where *we* originate the session, is the place that will own
//! and tear down a session — not here.)

use std::net::{IpAddr, Ipv4Addr};
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::Arc;
use std::time::Duration;

use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::TcpStream;

use crate::config::{Config, CAMERA_ONDEVICE_TARGET, OWN_PORT_AV};
use crate::own::Framer;

/// Monitor-session request, identical to `sender.rs` — the gateway streams every bus
/// frame after this.
const MONITOR_REQ: &[u8] = b"*99*1##";

/// The panel's own media-start frames target loopback (`127.0.0.1` = `127#0#0#1`); this
/// prefix marks "the encoder is now streaming" and is our arm signal. Our OWN added client
/// targets `camera_target` — an off-device host, or in on-device mode the loopback alias
/// `127.0.0.2` (`127#0#0#2`) — which differs from `127#0#0#1`, so it never matches this
/// prefix and we never re-arm off our own echo.
const DEVICE_MEDIA_PREFIX: &str = "*7*300#127#0#0#1#";

/// Whole-session teardown emitted by the panel when the A/V session ends.
const TEARDOWN: &str = "*7*0*##";

/// The on-device "camera is live now" signal file (issue #180). Its EXISTENCE — not its content — is the
/// signal, and it tracks the armed `:30007` siphon one-for-one: created the instant `arm()` succeeds
/// (real RTP is now flowing to go2rtc) and removed the instant the siphon is released. go2rtc's producer
/// wrapper (`camera-producer.sh`, generated by `Go2RtcConfig.BuildOnDeviceProducerScript`) reads it: when
/// present it `exec`s the LIVE feed (reads the runtime SDP), when absent the "Loading camera…" FILLER
/// (`-stream_loop` over [`LOADING_CLIP_PATH`]). The filler keeps go2rtc's lazy `exec:` producer always
/// fed with decodable H.264 so it never i/o-times-out during the panel's ~3 s SIP warm-up on a cold open
/// — Home Assistant holds the picture instantly instead of the stream dying to a black wait. On tmpfs
/// (`/var/run/btmqttd`, cleared every boot), so it defaults to "not live" after a reboot. MUST equal the
/// `SIG=` path the generated wrapper checks (`Go2RtcConfig.OnDeviceCameraLiveSignalPath`). `pub(crate)` so
/// `capture.rs` can gate a still grab on the SAME marker this task maintains — a snapshot must wait for the
/// live cutover so it never persists the "Loading camera…" filler frame — rather than re-spelling the path.
pub(crate) const CAMERA_LIVE_SIGNAL_PATH: &str = "/var/run/btmqttd/camera-live";

/// The on-device "the producer is actually serving the LIVE feed now" readiness file (issue #180). Written
/// by the go2rtc producer WRAPPER — NOT by this daemon: the wrapper creates it on the branch that `exec`s
/// the live feed and removes it on the branch that `exec`s the filler, BEFORE the `exec`, so it records the
/// branch the wrapper committed to even during its transient `/bin/sh` phase. This daemon only READS its
/// existence, in [`cut_over_to_live`], to confirm the filler→live cutover actually completed — a POSITIVE
/// signal that closes the sub-millisecond race a "no filler process in `/proc`" check could not (a wrapper
/// that read the marker absent and is mid-`exec` into the filler is not yet a matchable ffmpeg, but it has
/// already removed this file, so the cutover keeps retrying until live). On tmpfs (cleared every boot ⇒
/// absent = "not live yet"); the first cold producer's filler branch removes any stale copy. MUST equal the
/// `READY=` path the generated wrapper writes (`Go2RtcConfig.OnDeviceCameraLiveReadyPath`).
const LIVE_READY_PATH: &str = "/var/run/btmqttd/camera-live-ready";

/// A monotonic generation stamped once per SIPHON ARM (issue #180), so a consumer can bind a
/// capture to the SPECIFIC camera session it started in and detect a session change mid-capture. Bumped the
/// instant [`monitor`] arms a new siphon (a media-start after the previous session tore down) — NOT on the
/// per-iteration cutover retries, which never re-arm — so each armed session carries a distinct value.
/// `capture.rs`'s ring snapshot reads it when the camera first goes live and re-checks it before persisting:
/// the live-marker and its presence re-checks only test that SOME session is live, not that it is the SAME
/// one, so if the ringing session ends mid-capture and a different session (a manual view, possibly of
/// another entrance panel) re-arms the marker, this generation changes and the snapshot is discarded rather
/// than stored under the wrong ring event. Starts at 0; off-device it never bumps (the monitor never routes
/// there), so an off-device reader always sees a stable 0.
pub(crate) static CAMERA_SESSION_GEN: AtomicU64 = AtomicU64::new(0);

/// The "Loading camera…" filler clip the go2rtc producer wrapper loops while the siphon is NOT armed
/// (issue #180). Named here ONLY so the filler→live cutover can identify a running filler producer by its
/// `-i` argument (see [`PRODUCER_INPUTS`]); the clip itself is written to this path by the installer and
/// read by the generated wrapper, never by this daemon. MUST equal `Go2RtcConfig.OnDeviceLoadingClipPath`
/// and the wrapper's filler `-i`.
const LOADING_CLIP_PATH: &str = "/etc/btmqttd/go2rtc/loading.mp4";

/// The producer-input set the cutover respawn targets (issue #180): the runtime SDP OR the filler clip.
/// At the instant `arm()` succeeds the running go2rtc `exec:` producer is normally the FILLER (a cold
/// open Home Assistant is already watching), but it could already be the LIVE producer (a warm re-arm),
/// so the cutover SIGTERMs WHICHEVER is running — go2rtc then respawns the wrapper, which re-checks the
/// (now-present) signal file and `exec`s the live feed. The shared `/proc`-scan-then-SIGTERM primitive
/// lives in [`crate::procsig`]; `sprop.rs` passes it the runtime SDP alone (its learn only ever races the
/// live producer), so only THIS caller carries the wider set.
const PRODUCER_INPUTS: &[&str] = &[crate::sprop::SDP_PATH, LOADING_CLIP_PATH];

/// The FILLER-ONLY producer input (issue #180): identifies a running "Loading camera…" producer by its
/// `-i loading.mp4`, distinct from the live producer (`-i` runtime SDP). The cutover uses it two ways: the
/// per-iteration RETRY SIGTERMs with this set alone, so a retry can only ever restart a lingering filler and
/// NEVER churns the live feed; and [`cut_over_to_live`] then confirms the switch from the wrapper-written
/// [`LIVE_READY_PATH`] readiness file (a POSITIVE "wrapper committed to live" signal), not by re-scanning
/// `/proc` for a lingering filler (see there).
const FILLER_INPUTS: &[&str] = &[LOADING_CLIP_PATH];

/// The LIVE-ONLY producer input (issue #180): identifies a producer reading the runtime SDP (`-i`
/// [`crate::sprop::SDP_PATH`]), i.e. the LIVE feed — distinct from the filler. The session-EXIT cutover uses
/// it because that path fires on EVERY monitor drop, including cold sessions that never armed: targeting the
/// live producer alone cuts a now-SILENT live feed to the filler while leaving a cold filler (never silent)
/// untouched, so a bare monitor reconnect can't needlessly blip a "Loading…" that was already correct.
const LIVE_INPUTS: &[&str] = &[crate::sprop::SDP_PATH];

/// A/V daemon reply frames. These are the SAME OpenWebNet control frames as the monitor
/// ACK/NACK, so alias the shared `crate::own` definitions rather than re-spelling the bytes —
/// the control-frame definition then has one source of truth and cannot drift.
const AV_ACK: &[u8] = crate::own::ACK;
const AV_NACK: &[u8] = crate::own::NACK;

/// TOTAL attempts to send an "add client" frame (the loop runs `0..ADD_CLIENT_ATTEMPTS`): one
/// initial send plus NACK retries, 3 in all (≤ the reference project's cap).
const ADD_CLIENT_ATTEMPTS: u32 = 3;

/// How long to wait for the `:30007` ACK/NACK for one "add client" frame. Loopback, tiny
/// payload — a couple of seconds is generous and keeps a hung daemon from stalling arm.
const ACK_TIMEOUT: Duration = Duration::from_secs(2);

/// How long to wait for the monitor-session ACK (`*#*1##`) after `*99*1##` before treating
/// the session as refused and reconnecting. The gateway can accept the TCP connection yet
/// REFUSE the monitor with a NACK (e.g. monitor slots exhausted) and then go idle; a bound
/// here turns that into a backoff-reconnect instead of an infinite idle. Matches `sender.rs`.
const MONITOR_ACK_TIMEOUT: Duration = Duration::from_secs(5);

/// Ceiling on bytes accumulated while waiting for a control ACK/NACK. The reply is a 6-byte
/// `*#*1##` / `*#*0##` (at most preceded by a tiny banner or one batched media frame), so a
/// few KB is ample. The cap keeps a misbehaving peer that streams non-control bytes until the
/// timeout from ballooning the accumulation buffer — overflow is an error (reconnect / fail).
const MAX_CTRL_BYTES: usize = 4096;

/// Idle cap on a monitor read, so a quiet bus still lets the loop re-check `stopping`
/// and exit promptly at shutdown (the bus is rarely silent this long — dim/keepalive
/// frames arrive — but the bound guarantees responsiveness regardless).
const READ_IDLE: Duration = Duration::from_secs(15);

/// Reconnect backoff bounds for the monitor session (a gateway restart / boot race).
const BACKOFF_INIT: Duration = Duration::from_secs(1);
const BACKOFF_MAX: Duration = Duration::from_secs(30);

/// Bound on the camera-target DNS lookup. arm() runs inline in the session loop, so an
/// unbounded lookup against a misconfigured/unreachable resolver would block the monitor
/// task and could miss the rest of a call. On timeout we treat the target as unresolvable
/// (arm errors, is logged, and retries on the next media-start frame). A literal IPv4 — the
/// usual target — never reaches the lookup, and the broker host resolves from /etc/hosts.
const RESOLVE_TIMEOUT: Duration = Duration::from_secs(5);

/// A session that stayed up at least this long was HEALTHY: its eventual drop resets the
/// backoff, so a long-stable monitor that finally hiccups reconnects promptly instead of
/// inheriting a maxed-out delay (which could otherwise miss a ring). Mirrors `sender.rs`.
const HEALTHY_SESSION: Duration = Duration::from_secs(60);

/// Run the camera A/V task: keep an OWN monitor session up and drive the `:30007`
/// siphon from it. Owned by `main`, which sets `stopping` at shutdown; there is no
/// half-actuated state to drain (we never send a teardown), so exiting is immediate.
///
/// KNOWN LIMITATION (issue #103, deferred to a hardware-tested follow-up): the siphon is
/// SESSION-LOCAL — if the `:20000` monitor socket drops WHILE a call is live, `session`
/// returns, its `:30007` socket closes, and the fan-out stops for the rest of that call;
/// it re-arms only on the NEXT media-start frame. This is accepted for now because (a) on
/// this device the monitor and `bt_av_media` are the same BTicino stack, so a monitor drop
/// almost always means the media session ended too (nothing left to re-arm), and (b) the
/// robust fix — persisting the siphon across a monitor reconnect — must also reconcile a
/// teardown MISSED during the gap (else it stays wrongly "armed" and the NEXT call gets no
/// camera), which needs on-hardware validation to get right. Tracked for Phase 1 follow-up.
pub async fn run(cfg: Arc<Config>, stopping: Arc<AtomicBool>) {
    // Clear any STALE camera-live marker left by an unclean exit BEFORE the reconnect loop (issue #180).
    // The marker is on tmpfs (cleared on reboot) but SURVIVES a btmqttd restart / re-exec / crash within a
    // boot, and neither backstop clears it in that case: `main` ABORTS this task at shutdown, so `session`'s
    // per-exit clear can be bypassed, and the per-session TEARDOWN clear only fires once THIS run has armed
    // (a fresh session starts `siphon = None`). A leftover marker would make the first cold producer open
    // `exec` the LIVE SDP with no RTP behind it instead of the "Loading camera…" filler — recreating the
    // black cold-open. Clearing it here guarantees a cold open always starts on the filler. On-device-only +
    // best-effort (a no-op off-device, and where the marker is already absent — the usual case).
    // ...and reset any go2rtc producer that SURVIVED this restart (issue #180, Finding B). A btmqttd
    // restart / re-exec / crash within a boot drops the old siphon but does NOT stop a go2rtc `exec:`
    // producer already running: its live-branch ffmpeg keeps reading the now-SILENT live SDP and would sit
    // there until go2rtc's ~15 s i/o-timeout finally cut it back to the filler on its own. Clearing the
    // marker and respawning it here (the respawn GATED on the clear succeeding, so a lost removal never
    // serves the stale marker's live SDP) makes the wrapper re-read the now-absent marker and cut to the
    // "Loading camera…" filler PROMPTLY instead of a black wait. On-device-only and best-effort: a no-op on
    // a clean boot, where no producer is running yet.
    clear_and_respawn_to_filler(
        &cfg,
        PRODUCER_INPUTS,
        "reset any surviving go2rtc producer to the loading filler after a btmqttd restart",
    )
    .await;
    let mut backoff = BACKOFF_INIT;
    while !stopping.load(Ordering::Relaxed) {
        let start = tokio::time::Instant::now();
        match session(&cfg, &stopping).await {
            // A clean return means `stopping` was observed — leave the loop.
            Ok(()) => break,
            // Log host AND port (and the "unavailable" suffix) so a mismatched OWN_HOST/port is
            // diagnosable — same shape as sender.rs's monitor error.
            Err(e) => eprintln!(
                "btmqttd: camera monitor {}:{} unavailable: {e}",
                cfg.own_host, cfg.own_port_mon
            ),
        }
        if stopping.load(Ordering::Relaxed) {
            break;
        }
        // A session that ran healthy for a while shouldn't inherit a maxed-out backoff from
        // earlier startup churn — reset so the reconnect is prompt (a 30 s wait could miss a ring).
        if start.elapsed() >= HEALTHY_SESSION {
            backoff = BACKOFF_INIT;
        }
        tokio::time::sleep(backoff).await;
        backoff = (backoff * 2).min(BACKOFF_MAX);
    }
}

/// One monitor session: connect and request the stream, then drive the arm/disarm loop to completion and —
/// on ANY exit — clear the `camera-live` signal and cut a still-attached LIVE producer back to the filler.
/// Returns `Ok(())` only when `stopping` was seen; any I/O error is returned so `run` backs off and
/// reconnects. The armed `:30007` socket lives in `monitor`'s `siphon`; its exit (on teardown, error, or
/// return) drops it and stops the fan-out.
async fn session(cfg: &Arc<Config>, stopping: &Arc<AtomicBool>) -> std::io::Result<()> {
    let mut sock = TcpStream::connect((cfg.own_host.as_str(), cfg.own_port_mon)).await?;
    sock.write_all(MONITOR_REQ).await?;
    sock.flush().await?;

    // Drive the monitor to completion; whatever ends it (a clean stop or an I/O error), the armed :30007
    // siphon — if any — drops with `sock`, so the fan-out has stopped and any producer reading the runtime
    // SDP is now SILENT.
    let result = monitor(&mut sock, cfg, stopping).await;
    // On ANY monitor exit, clear the live signal (issue #180) and respawn the LIVE producer to the filler —
    // UNCONDITIONALLY, not gated on whether the in-monitor cutover confirmed. A producer can reach the live
    // SDP ASYNCHRONOUSLY after `cut_over_to_live` returned false (the SIGTERM'd filler exits and go2rtc
    // restarts the wrapper onto the now-present marker), so "the cutover never confirmed" is NOT proof that
    // no producer is live; gating the respawn on it would leave that async-live viewer on the silent SDP
    // until go2rtc's i/o-timeout. `clear_and_respawn_to_filler` still respawns ONLY if the clear is
    // confirmed (a lost removal must not serve the stale marker's live SDP). Target [`LIVE_INPUTS`] (the SDP
    // producer only): this fires on EVERY monitor drop, so a cold session that only ever served the filler
    // must not have it needlessly restarted. On-device-only no-op off-device (and when nothing is attached).
    clear_and_respawn_to_filler(
        cfg,
        LIVE_INPUTS,
        "cut the live feed back to the loading filler after the camera monitor session dropped",
    )
    .await;
    result
}

/// The monitor read/arm loop for one connected session (split from [`session`] so the caller can clear
/// the `camera-live` signal and respawn on EVERY exit path, not just the clean ones). Owns the armed
/// `:30007` `siphon` socket, so returning from here drops it and stops the fan-out. Returns `Ok(())` only
/// when `stopping` was seen; any I/O error is propagated so `run` backs off and reconnects. The back-to-
/// filler cutover on exit is the caller's ([`session`]) responsibility and is UNCONDITIONAL — it does not
/// depend on any state this loop reports — so no out-parameter is needed (issue #180).
async fn monitor(
    sock: &mut TcpStream,
    cfg: &Arc<Config>,
    stopping: &Arc<AtomicBool>,
) -> std::io::Result<()> {
    let mut framer = Framer::default();
    let mut buf = [0u8; 4096];
    let mut frames: Vec<String> = Vec::new();
    let mut siphon: Option<TcpStream> = None; // Some(_) while our client is added
    // `live_marked`: whether the camera-live marker is confirmed set AND the go2rtc producer cut over for
    // the CURRENT `siphon` (issue #180, Finding A). Tracked ALONGSIDE `siphon` because the marker write /
    // cutover confirmation can fail transiently even though the fan-out armed cleanly: the siphon is then
    // `Some` while the viewer is still on the "Loading…" filler. This flag lets the loop RE-attempt the
    // cutover each pass (see below) instead of leaving it stuck until TEARDOWN. Reset to false whenever
    // `siphon` drops. Purely LOCAL: the session-exit respawn no longer keys off it (see [`session`]).
    let mut live_marked = false;

    // Confirm the monitor ACK before trusting the stream. The gateway may accept the TCP
    // connection yet REFUSE the monitor with a NACK (`*#*0##`) and then stay idle — the
    // `Framer` DROPS the control frames, so without a raw-byte scan here the read loop would
    // just time out on `READ_IDLE` forever and never reconnect. `sender.rs` does the same.
    // Bytes trailing the ACK are handed to the framer, so a bus frame batched with the ACK
    // isn't lost. Accumulate across reads: TCP may split the 6-byte ACK.
    {
        let mut pre: Vec<u8> = Vec::new();
        let acked = tokio::time::timeout(
            MONITOR_ACK_TIMEOUT,
            read_until_ack_or_nack(sock, &mut pre),
        )
        .await
        .map_err(|_| std::io::Error::new(std::io::ErrorKind::TimedOut, "monitor ACK timed out"))??;
        if !acked {
            // The gateway REFUSED the monitor session — back off and reconnect (see `run`).
            return Err(std::io::Error::new(
                std::io::ErrorKind::ConnectionRefused,
                "monitor session refused (NACK)",
            ));
        }
        // Frame only the bytes AFTER the ACK (any pre-ACK banner is not a frame). The helper
        // returned Ok(true) only on a complete ACK, so the position is always present.
        let pos = find_sub(&pre, AV_ACK).expect("ACK present when read_until_ack_or_nack is true");
        framer.push(&pre[pos + AV_ACK.len()..], &mut frames);
    }

    loop {
        if stopping.load(Ordering::Relaxed) {
            return Ok(());
        }
        // Process frames collected so far — the post-ACK batch on the first pass, then each
        // freshly-read batch. Kept at the top so the initial batch isn't skipped.
        for f in &frames {
            if f == TEARDOWN {
                // Panel ended the session — our added client is gone with it; drop ours.
                if siphon.take().is_some() {
                    // Real RTP has stopped: cut a still-attached consumer back to the "Loading camera…"
                    // filler (issue #180), so a still-connected Home Assistant producer doesn't sit on the
                    // silent LIVE SDP for go2rtc's ~15 s i/o-timeout. `clear_and_respawn_to_filler` clears the
                    // marker FIRST and respawns ONLY if that is confirmed (a lost removal must not serve the
                    // stale marker's live SDP); if the clear fails, the producer falls back on go2rtc's
                    // i/o-timeout AND the session-exit cutover retries it unconditionally, so the viewer is
                    // never abandoned. This fires only on a genuine media-end TEARDOWN — the make-before-break
                    // SIP refresh keeps media continuous and never emits `*7*0*##` — and the respawn is a
                    // no-op when nobody is watching. Reset `live_marked`: its only role is the retry gate
                    // below (also guarded by `siphon.is_some()`, now `None`), so this is tidiness for a re-arm.
                    live_marked = false;
                    if clear_and_respawn_to_filler(
                        cfg,
                        PRODUCER_INPUTS,
                        "cut the live feed back to the loading filler after the panel session ended",
                    )
                    .await
                    {
                        eprintln!("btmqttd: camera siphon released (session ended)");
                    } else {
                        eprintln!(
                            "btmqttd: camera siphon released (session ended) but the live marker could not be cleared; the session-exit cutover will retry it"
                        );
                    }
                }
            } else if siphon.is_none() && f.starts_with(DEVICE_MEDIA_PREFIX) {
                // Media is live now: add our client and hand HA the stream.
                match arm(cfg).await {
                    Ok(s) => {
                        // The fan-out IS armed — record it UNCONDITIONALLY so a later media-start frame
                        // does not re-enter this branch (its guard is `siphon.is_none()`). The filler→live
                        // cutover is a SEPARATE concern tracked by `live_marked`: `cut_over_to_live`
                        // creates the marker and, only if that succeeds, respawns the producer, returning
                        // whether the CURRENT siphon is now confirmed live. If the marker write failed (a
                        // transient tmpfs blip) it returns false and the per-iteration retry below re-drives
                        // the cutover each loop pass — so the viewer reaches the live feed within seconds
                        // instead of staying on "Loading…" until TEARDOWN (issue #180, Finding A).
                        siphon = Some(s);
                        // Stamp a fresh session generation BEFORE creating the live marker below, so any
                        // consumer that observes this session's marker also observes its generation (issue
                        // #180). Bumped only here — on a genuine re-arm — never on the retries.
                        CAMERA_SESSION_GEN.fetch_add(1, Ordering::Relaxed);
                        live_marked = cut_over_to_live(
                            cfg,
                            PRODUCER_INPUTS,
                            "cut the loading filler over to the live camera feed",
                            true, // arm time: a filler producer is normally running (HA is watching) — a
                                  // missing one is unexpected and worth a log line.
                        )
                        .await;
                        eprintln!(
                            "btmqttd: camera siphon armed -> {}:{}/{} (branch {})",
                            cfg.camera_target,
                            cfg.camera_video_port,
                            cfg.camera_audio_port,
                            cfg.camera_branch
                        );
                    }
                    Err(e) => eprintln!("btmqttd: camera siphon arm failed: {e}"),
                }
            }
        }
        frames.clear();

        // Retry the filler→live cutover while the siphon is armed but not yet CONFIRMED live (issue #180,
        // Finding A). This covers two transient gaps: `arm()` succeeded but `set_camera_live_signal` failed
        // (fan-out flowing while the viewer is on "Loading…"), and the respawn raced a filler wrapper still
        // mid-exec so one is still looping. It respawns the FILLER ONLY ([`FILLER_INPUTS`]) so a retry can
        // never SIGTERM the live producer, and `cut_over_to_live` confirms the switch from the wrapper's own
        // readiness file ([`LIVE_READY_PATH`]) — the positive "wrapper committed to live" signal — before it
        // reports live. Runs each loop pass — as frames arrive (frequently, on a live session) or on the
        // READ_IDLE wakeup — so it recovers within seconds. On-device-gated and best-effort (off-device
        // `set_camera_live_signal` is false, so this reports not-live without touching a producer or the
        // readiness file, and — the off-device target never routes here — it never spins). Passes
        // `warn_if_none: false`: this path runs precisely while the siphon is armed but UNWATCHED (no
        // consumer ⇒ no producer to respawn yet), so a zero-producer respawn is the normal steady state here
        // and must not spam the log at the loop cadence.
        if siphon.is_some() && !live_marked {
            live_marked = cut_over_to_live(
                cfg,
                FILLER_INPUTS,
                "retry cutting the loading filler over to the live camera feed",
                false,
            )
            .await;
        }

        let n = match tokio::time::timeout(READ_IDLE, sock.read(&mut buf)).await {
            Ok(Ok(0)) => {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::UnexpectedEof,
                    "monitor closed",
                ))
            }
            Ok(Ok(n)) => n,
            Ok(Err(e)) => return Err(e),
            Err(_) => continue, // idle: re-check `stopping`, keep reading
        };
        framer.push(&buf[..n], &mut frames);
    }
}

/// Open a `:30007` session and add our video + audio UDP clients pointing at
/// `camera_target`. Returns the still-open socket (kept for the session lifetime; the
/// daemon drops the clients when the connection closes or the panel tears down). Errors
/// if the target can't be resolved or the daemon NACKs an "add client" past its retries.
async fn arm(cfg: &Arc<Config>) -> std::io::Result<TcpStream> {
    // Fail fast on a port config the fan-out can't use (a hand-edited / corrupt conf: config.rs
    // already maps 0 to the default, but guard here too, and reject equal video/audio ports which
    // would collide two RTP streams on one UDP port and break go2rtc's demux).
    if cfg.camera_video_port == 0 || cfg.camera_audio_port == 0 {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "camera video/audio port is 0",
        ));
    }
    if cfg.camera_video_port == cfg.camera_audio_port {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "camera video and audio ports must differ",
        ));
    }
    let ip = resolve_ipv4(&cfg.camera_target).await.ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            format!("camera_target '{}' did not resolve to an IPv4", cfg.camera_target),
        )
    })?;
    // Reject an unroutable target (pure + socket-free, so it is unit-testable without a
    // connection to bt_av_media — see `check_camera_target` for the full rationale).
    check_camera_target(ip, cfg.camera_ondevice)?;
    let o = ip.octets();
    let ipf = format!("{}#{}#{}#{}", o[0], o[1], o[2], o[3]);
    let video = format!("*7*300#{ipf}#{}#{}*##", cfg.camera_video_port, cfg.camera_branch);
    let audio = format!("*7*300#{ipf}#{}#2*##", cfg.camera_audio_port);

    // 127.0.0.1 BY DESIGN: `bt_av_media` is an on-device daemon and `:30007` is a command (write)
    // endpoint — like the `:30006` gateway port in receiver.rs, which is also fixed to loopback.
    // OWN_HOST governs only the MONITOR (read) endpoint (see receiver.rs / sender.rs).
    let mut sock = TcpStream::connect(("127.0.0.1", OWN_PORT_AV)).await?;
    add_client(&mut sock, &video).await?;
    add_client(&mut sock, &audio).await?;
    Ok(sock)
}

/// Drive the filler→live cutover for the CURRENTLY-armed siphon (issue #180): create the camera-live
/// marker and, ONLY if that succeeded, respawn the go2rtc producer(s) in `respawn_inputs` so a running
/// wrapper re-reads the now-present marker and `exec`s the live feed. Returns whether the cutover is
/// CONFIRMED complete — the caller's `live_marked`.
///
/// Completion is defined as "the wrapper has COMMITTED to the live branch", read from the wrapper-written
/// [`LIVE_READY_PATH`] readiness file — a POSITIVE signal, not the absence of a filler in `/proc`. The
/// SIGTERM respawn is best-effort and can miss a producer whose wrapper is momentarily still in its
/// transient `/bin/sh` exec phase (not yet a matchable ffmpeg); a "no filler process" check would then
/// wrongly report complete, set `live_marked`, DISABLE the monitor loop's per-iteration retry, and strand
/// the viewer on a filler about to `exec`. The wrapper instead records its branch decision in
/// [`LIVE_READY_PATH`] BEFORE it `exec`s (create for live, remove for filler), so even mid-exec the file
/// reflects the truth: a wrapper that took the filler removed it ⇒ this returns false ⇒ the retry re-drives
/// the cutover until a wrapper takes the LIVE branch and creates it. This never churns the live producer:
/// once the wrapper is live the file exists and the retry stops; an armed-but-UNWATCHED siphon has no
/// producer, so the file stays absent and the retry keeps cheaply re-asserting the marker (respawning only
/// the filler, [`FILLER_INPUTS`], which is a no-op when none runs) until a viewer connects and goes live.
///
/// ORDER MATTERS: marker FIRST, then respawn — the respawned wrapper must observe the marker present, or it
/// would `exec` the filler AGAIN while the siphon is armed. Gating everything on the marker write is what
/// makes a transient marker-write failure SAFE: it leaves the running filler untouched (a stale "loading",
/// never a black wait) and returns false, so the retry re-drives the cutover next pass. On-device-only:
/// [`set_camera_live_signal`] creates nothing and returns false off-device — there is no on-device
/// producer/filler and the target never routes here in practice — so this returns false WITHOUT touching a
/// producer or the readiness file. Shared by the arm branch (which respawns [`PRODUCER_INPUTS`], catching a
/// filler OR a stale live producer) and the retry (which respawns [`FILLER_INPUTS`] only, so it can't churn
/// the live feed) so the "marker-then-respawn-then-confirm" sequence lives in ONE place and can't drift.
async fn cut_over_to_live(
    cfg: &Arc<Config>,
    respawn_inputs: &'static [&'static str],
    reason: &'static str,
    warn_if_none: bool,
) -> bool {
    if !set_camera_live_signal(cfg).await {
        return false;
    }
    // The marker exists now, so a respawned wrapper reads "live". SIGTERM whichever producer(s) the caller
    // targets so go2rtc respawns them onto the live feed. `warn_if_none` is forwarded so the RETRY caller
    // stays quiet in the armed-but-unwatched steady state (no producer yet) while the arm-time caller still
    // logs a genuinely-missing producer.
    crate::procsig::respawn_go2rtc_producers(respawn_inputs, reason, warn_if_none).await;
    // Confirm the switch from the wrapper's own readiness file: complete only once a wrapper has committed
    // to the LIVE branch (created [`LIVE_READY_PATH`]). A wrapper still mid-exec into the filler has already
    // removed it, so this reports NOT complete and the loop retries — closing the `/bin/sh`-exec race.
    live_ready_present().await
}

/// Whether the wrapper's [`LIVE_READY_PATH`] readiness file exists — i.e. the producer wrapper has
/// committed to the LIVE branch (issue #180). Async `tokio::fs` so it never blocks the single-threaded
/// runtime; `metadata(..).is_ok()` treats any stat error (including "not present") as "not ready", which is
/// the conservative direction for the cutover (keep retrying). The wrapper only ever writes this file
/// on-device, so off-device it is always absent — but `cut_over_to_live` returns before reaching here
/// off-device (its `set_camera_live_signal` is false), so this is on-device-only in practice.
async fn live_ready_present() -> bool {
    tokio::fs::metadata(LIVE_READY_PATH).await.is_ok()
}

/// Create the [`CAMERA_LIVE_SIGNAL_PATH`] marker (issue #180), best-effort, ON-DEVICE ONLY. Its presence
/// tells go2rtc's producer wrapper to `exec` the LIVE feed instead of the "Loading camera…" filler.
/// Called the instant the siphon arms and BEFORE the cutover respawn, so the fresh producer observes it.
///
/// RETURNS whether the marker now EXISTS on disk — `true` only when the create succeeded on-device. The
/// caller GATES the cutover respawn on this: respawning with the marker still absent would SIGTERM the
/// running filler producer only for go2rtc to respawn the wrapper, read "not live", and pick the filler
/// again while the siphon is armed (viewer stuck on "Loading…"). On a failure it is logged and non-fatal:
/// go2rtc keeps serving the filler (a stale "loading", never a black wait) until the next arm re-tries.
/// Off-device there is no on-device producer/filler, so nothing is created and `false` is returned (the
/// caller then skips the respawn, which is a no-op off-device regardless). The path-injected
/// [`set_signal_at`] does the work (unit-tested on a temp file).
async fn set_camera_live_signal(cfg: &Arc<Config>) -> bool {
    if !cfg.camera_ondevice {
        return false;
    }
    match set_signal_at(CAMERA_LIVE_SIGNAL_PATH).await {
        Ok(()) => true,
        Err(e) => {
            eprintln!(
                "btmqttd: camera: could not create the live signal {CAMERA_LIVE_SIGNAL_PATH} ({e}); go2rtc keeps serving the loading filler"
            );
            false
        }
    }
}

/// [`set_camera_live_signal`] with the target path injected, so the create-parent-then-touch behaviour is
/// unit-tested against a temp file rather than the fixed tmpfs path. Ensures the parent dir exists first
/// (`go2rtcd` makes `/var/run/btmqttd` at boot, but a race — or a manual go2rtc start before the dir is
/// assembled — must not leave the arm unable to signal), then creates the marker; only its EXISTENCE is
/// the signal, so the file is left empty.
async fn set_signal_at(path: &str) -> std::io::Result<()> {
    if let Some(dir) = std::path::Path::new(path).parent() {
        let _ = tokio::fs::create_dir_all(dir).await;
    }
    tokio::fs::File::create(path).await.map(|_| ())
}

/// Attempts to remove the marker before giving up (issue #180). A LOST removal leaves a STALE marker that
/// makes the next producer serve the silent live SDP instead of the filler, so a transient tmpfs blip is
/// retried a few times rather than accepted on the first error (a tmpfs unlink of a file we own essentially
/// never fails, but the consequence of a lost one is bad enough to retry).
const MARKER_CLEAR_ATTEMPTS: u32 = 3;
/// Delay between marker-removal retries ([`MARKER_CLEAR_ATTEMPTS`]).
const MARKER_CLEAR_RETRY: Duration = Duration::from_millis(50);

/// Remove the [`CAMERA_LIVE_SIGNAL_PATH`] marker (issue #180), ON-DEVICE ONLY, so the next cold producer
/// open serves the filler again. RETURNS whether the marker is confirmed ABSENT afterwards — `true` when it
/// was removed, was already gone, or off-device (no marker exists there). Callers GATE the producer respawn
/// on this (see [`clear_and_respawn_to_filler`]): respawning while the marker is still PRESENT would make
/// go2rtc re-read it and serve the silent live SDP again instead of the filler, and on TEARDOWN `live_marked`
/// is cleared so no retry follows — so a failed removal must NOT respawn. A transient failure is retried up
/// to [`MARKER_CLEAR_ATTEMPTS`] times; a persistent one is logged and returns `false`, leaving the running
/// producer to fall back on go2rtc's own i/o-timeout (the pre-#180 behaviour — no worse). The path-injected
/// [`clear_signal_at`] does the work (unit-tested; an already-absent marker is `Ok` ⇒ `true`).
async fn clear_camera_live_signal(cfg: &Arc<Config>) -> bool {
    if !cfg.camera_ondevice {
        return true; // off-device: no marker/filler exists, so it is trivially "absent"
    }
    for attempt in 1..=MARKER_CLEAR_ATTEMPTS {
        match clear_signal_at(CAMERA_LIVE_SIGNAL_PATH).await {
            Ok(()) => return true,
            Err(e) => {
                eprintln!(
                    "btmqttd: camera: could not remove the live signal {CAMERA_LIVE_SIGNAL_PATH} (attempt {attempt}/{MARKER_CLEAR_ATTEMPTS}): {e}"
                );
                if attempt < MARKER_CLEAR_ATTEMPTS {
                    tokio::time::sleep(MARKER_CLEAR_RETRY).await;
                }
            }
        }
    }
    eprintln!(
        "btmqttd: camera: the live signal {CAMERA_LIVE_SIGNAL_PATH} could not be cleared; skipping the producer respawn so the wrapper does not re-read the stale marker (go2rtc's i/o-timeout will fall back)"
    );
    false
}

/// Clear the marker and — ONLY if the clear is CONFIRMED (marker now absent) — respawn the go2rtc producer
/// so its wrapper re-reads the absent marker and cuts to the "Loading camera…" filler (issue #180). Returns
/// whether that back-to-filler cutover completed. Shared by every "media ended → filler" path (the panel
/// TEARDOWN, the monitor-drop session exit, the startup reset, and shutdown) so the marker-then-gated-respawn
/// order lives in ONE place. If the clear fails the respawn is SKIPPED — respawning would make the wrapper
/// re-read the stale PRESENT marker and serve the silent live SDP instead of the filler; the running producer
/// then falls back on go2rtc's own i/o-timeout. On-device-gated: off-device the clear is a no-op returning
/// `true` and there is no producer to respawn, so this returns `true` without touching a producer.
///
/// `respawn_inputs` names WHICH producer(s) to cut: [`PRODUCER_INPUTS`] (SDP or filler) for the lifecycle
/// resets that may find either survivor (TEARDOWN, startup, shutdown), or [`LIVE_INPUTS`] (SDP only) for the
/// session-EXIT cutover, which fires on every monitor drop and must leave a cold filler untouched.
async fn clear_and_respawn_to_filler(
    cfg: &Arc<Config>,
    respawn_inputs: &'static [&'static str],
    reason: &'static str,
) -> bool {
    if !clear_camera_live_signal(cfg).await {
        return false;
    }
    if cfg.camera_ondevice {
        // Lifecycle reset (teardown / session-exit / startup / shutdown): a producer is normally attached, so
        // log a missing one (`warn_if_none: true`). This is not the high-cadence retry path.
        crate::procsig::respawn_go2rtc_producers(respawn_inputs, reason, true).await;
    }
    true
}

/// Best-effort camera-live cleanup for daemon SHUTDOWN (issue #180). When btmqttd is STOPPED (`btmqttd
/// stop`, or a re-exec) the A/V task is ABORTED (`main`'s `stop()` calls `JoinHandle::abort`), so neither
/// [`session`]'s per-exit clear nor [`run`]'s startup clear runs on the way down and the `camera-live`
/// marker would survive on tmpfs. go2rtc is separately supervised, so on a plain stop it keeps running and
/// a new producer would read the stale marker and `exec` the now-SILENT live SDP (the siphon socket is
/// gone) instead of the "Loading camera…" filler — a black wait until btmqttd starts again. `main` calls
/// this from the shutdown path (AFTER the task is aborted, so it can't re-mark) to clear the marker AND
/// respawn any running producer to the filler — mirroring the TEARDOWN/monitor-drop branches, since
/// clearing alone would leave an attached viewer on the silent SDP until go2rtc's i/o-timeout. Best-effort
/// and on-device-only (a no-op off-device, on a clean marker, and where no producer is attached or go2rtc
/// is going down too).
pub(crate) async fn shutdown_cleanup(cfg: &Arc<Config>) {
    clear_and_respawn_to_filler(
        cfg,
        PRODUCER_INPUTS,
        "cut the live feed back to the loading filler as btmqttd shuts down",
    )
    .await;
}

/// [`clear_camera_live_signal`] with the target path injected (unit-tested on a temp file). An
/// ALREADY-ABSENT file is SUCCESS — the common case, since most sessions never arm and this also runs as
/// the per-session backstop in [`session`], so a missing marker must not surface as an error to log.
async fn clear_signal_at(path: &str) -> std::io::Result<()> {
    match tokio::fs::remove_file(path).await {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e),
    }
}

/// Validate the resolved siphon target, applying the on-device loopback carve-out. Pure (no
/// I/O), so it is unit-testable without opening a socket to `bt_av_media`.
///
/// With an off-device go2rtc/HA host:
///   * loopback (127/8) is never a real off-device destination, so it is unroutable — and
///     `127.0.0.1` SPECIFICALLY is worse still: our add-client frame would be
///     `*7*300#127#0#0#1#…`, identical to DEVICE_MEDIA_PREFIX, so our own frame echoing on the
///     monitor could be misread as a media-start "arm" signal;
///   * the unspecified 0.0.0.0 is a local bind wildcard, not a routable host — the daemon would
///     report the siphon armed while no receiver ever gets the RTP.
///
/// EXCEPTION — on-device mode (issue #120): go2rtc runs ON the panel and listens on loopback, so
/// the siphon target IS loopback by design. Permit EXACTLY [`CAMERA_ONDEVICE_TARGET`]
/// (`127.0.0.2`): it routes via `lo` to go2rtc, and its `*7*300#127#0#0#2#…` frame does NOT match
/// DEVICE_MEDIA_PREFIX (`…#127#0#0#1#`), so it never re-arms us. `127.0.0.1` (the collision) and
/// `0.0.0.0` (bind wildcard) stay rejected even in on-device mode — the carve-out is a single
/// exact address, not a blanket loopback allow.
fn check_camera_target(ip: Ipv4Addr, camera_ondevice: bool) -> std::io::Result<()> {
    let ondevice_ok = camera_ondevice && ip == CAMERA_ONDEVICE_TARGET;
    if !ondevice_ok && (ip.is_loopback() || ip.is_unspecified()) {
        // Mode-specific message: on-device mode DOES permit one loopback address (127.0.0.2),
        // so the generic "no loopback" wording would misdescribe why an on-device target was
        // rejected. Off-device, no loopback/unspecified address is ever valid.
        let msg: &str = if camera_ondevice {
            "camera_target in on-device mode must be 127.0.0.2 (the CAMERA_ONDEVICE_TARGET loopback alias)"
        } else {
            "camera_target must be a routable address (not loopback or 0.0.0.0)"
        };
        return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, msg));
    }
    Ok(())
}

/// Write one "add client" frame and wait for the daemon's ACK, resending on a NACK for up to
/// [`ADD_CLIENT_ATTEMPTS`] total tries. A NACK on the last try, an EOF, or a timeout is an error.
async fn add_client(sock: &mut TcpStream, frame: &str) -> std::io::Result<()> {
    for _ in 0..ADD_CLIENT_ATTEMPTS {
        sock.write_all(frame.as_bytes()).await?;
        sock.flush().await?;

        // Wait for the daemon's control reply (shared accumulate/scan/cap helper: TCP may split
        // the 6-byte `*#*1##` / `*#*0##` across reads). Bounded by ACK_TIMEOUT.
        let mut resp: Vec<u8> = Vec::new();
        let acked = tokio::time::timeout(ACK_TIMEOUT, read_until_ack_or_nack(sock, &mut resp))
            .await
            .map_err(|_| {
                std::io::Error::new(std::io::ErrorKind::TimedOut, "av daemon ack timed out")
            })??;
        if acked {
            return Ok(());
        }
        // NACK: loop and retry the same frame.
    }
    Err(std::io::Error::other(
        "av daemon NACKed add-client past retries",
    ))
}

/// Resolve `host` to an IPv4 for the OWN `*7*300#a#b#c#d#…` target: a literal dotted
/// IPv4 is used as-is; otherwise the first IPv4 from a DNS lookup. `None` if neither
/// yields an IPv4 (an IPv6-only or unresolvable target — the fan-out frame is IPv4-only).
async fn resolve_ipv4(host: &str) -> Option<Ipv4Addr> {
    if let Ok(v4) = host.parse::<Ipv4Addr>() {
        return Some(v4);
    }
    // Port 0: we only want the address; the port in the frame comes from config. Bound the
    // lookup so a hung resolver can't stall the monitor task (timeout ⇒ unresolvable ⇒ None).
    let addrs = match tokio::time::timeout(RESOLVE_TIMEOUT, tokio::net::lookup_host((host, 0))).await
    {
        Ok(Ok(addrs)) => addrs,
        _ => return None, // resolver error or timeout
    };
    for a in addrs {
        if let IpAddr::V4(v4) = a.ip() {
            return Some(v4);
        }
    }
    None
}

/// The start index of the first occurrence of `needle` in `haystack`, if any (small
/// buffers; a plain scan is ample). Used both to detect the ACK/NACK control frames and to
/// slice past the monitor ACK so trailing bus bytes still reach the framer.
fn find_sub(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    haystack.windows(needle.len()).position(|w| w == needle)
}

/// Read from `sock` into `acc`, accumulating ACROSS reads, until a COMPLETE control frame
/// appears: `Ok(true)` on ACK (`*#*1##`), `Ok(false)` on NACK (`*#*0##`). A single `read`
/// does not preserve OWN frame boundaries, so the 6-byte reply may be split across packets;
/// this keeps reading until one completes. Errors on EOF, on an I/O failure, or when `acc`
/// exceeds [`MAX_CTRL_BYTES`] (a peer streaming non-control bytes — the cap stops unbounded
/// allocation). Callers add their OWN timeout and interpret the bool (the monitor also reads
/// the ACK's position out of `acc` afterwards to frame the bytes trailing it). Shared by the
/// monitor handshake and `add_client` so the accumulate/scan/cap logic lives in one place.
async fn read_until_ack_or_nack(
    sock: &mut TcpStream,
    acc: &mut Vec<u8>,
) -> std::io::Result<bool> {
    let mut buf = [0u8; 4096];
    loop {
        let n = sock.read(&mut buf).await?;
        if n == 0 {
            return Err(std::io::Error::new(
                std::io::ErrorKind::UnexpectedEof,
                "peer closed before ACK/NACK",
            ));
        }
        acc.extend_from_slice(&buf[..n]);
        // Decide on whichever control frame appears FIRST in the stream. The panel sends
        // exactly one reply per request, so normally only one is ever present; but if a
        // misbehaving peer emitted both in one buffer (a NACK then a stray ACK), honouring
        // byte order is safer than letting a trailing ACK override the earlier refusal.
        match (find_sub(acc, AV_ACK), find_sub(acc, AV_NACK)) {
            (Some(a), Some(n)) => return Ok(a < n),
            (Some(_), None) => return Ok(true),
            (None, Some(_)) => return Ok(false),
            (None, None) => {}
        }
        if acc.len() > MAX_CTRL_BYTES {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "ACK/NACK not seen within the control-buffer cap",
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arm_signal_is_only_the_loopback_media_frame() {
        // The panel's own media-start (loopback target) arms us…
        assert!("*7*300#127#0#0#1#5007#0*##".starts_with(DEVICE_MEDIA_PREFIX));
        assert!("*7*300#127#0#0#1#5002#1*##".starts_with(DEVICE_MEDIA_PREFIX));
        // …but our OWN fan-out frame (a non-loopback target) does not, so we never
        // re-arm off our own echo on the monitor.
        assert!(!"*7*300#192#168#1#50#40000#1*##".starts_with(DEVICE_MEDIA_PREFIX));
        // The on-device loopback alias 127.0.0.2 (`127#0#0#2`) likewise does NOT match — its last
        // octet differs from the panel's `127#0#0#1`, so the on-device feed never self-arms either.
        assert!(!"*7*300#127#0#0#2#40000#1*##".starts_with(DEVICE_MEDIA_PREFIX));
        // The teardown is matched exactly.
        assert_eq!(TEARDOWN, "*7*0*##");
    }

    #[test]
    fn find_sub_locates_ack_and_nack() {
        assert_eq!(find_sub(b"*#*1##", AV_ACK), Some(0));
        assert_eq!(find_sub(b"junk*#*1##junk", AV_ACK), Some(4));
        assert_eq!(find_sub(b"*#*0##", AV_NACK), Some(0));
        assert_eq!(find_sub(b"*#*1##", AV_NACK), None);
        assert_eq!(find_sub(b"", AV_ACK), None);
    }

    #[test]
    fn add_client_accepts_an_ack_split_across_reads() {
        // TCP can split the 6-byte `*#*1##` across packets; `add_client` must accumulate until
        // the ACK is COMPLETE rather than misread the first fragment as an unexpected reply.
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
            let addr = listener.local_addr().unwrap();
            let server = tokio::spawn(async move {
                let (mut s, _) = listener.accept().await.unwrap();
                let mut b = [0u8; 64];
                let _ = s.read(&mut b).await.unwrap(); // consume the add-client frame
                // Reply with the ACK deliberately fragmented into two writes.
                s.write_all(b"*#").await.unwrap();
                s.flush().await.unwrap();
                s.write_all(b"*1##").await.unwrap();
                s.flush().await.unwrap();
            });
            let mut client = TcpStream::connect(addr).await.unwrap();
            add_client(&mut client, "*7*300#1#2#3#4#40000#1*##").await.unwrap();
            server.await.unwrap();
        });
    }

    #[test]
    fn add_client_errors_on_a_nack() {
        // A complete NACK past the retries surfaces as an error (so arm() fails and is logged).
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
            let addr = listener.local_addr().unwrap();
            let server = tokio::spawn(async move {
                let (mut s, _) = listener.accept().await.unwrap();
                let mut b = [0u8; 64];
                // NACK every add-client attempt (ADD_CLIENT_ATTEMPTS of them). Best-effort I/O:
                // the client may drop after the last NACK, so bail out on an I/O error rather than
                // panicking — that keeps `server.await.unwrap()` below meaningful (it then surfaces
                // only a genuine task panic, not an expected disconnect race).
                for _ in 0..ADD_CLIENT_ATTEMPTS {
                    if s.read(&mut b).await.is_err() {
                        break;
                    }
                    if s.write_all(AV_NACK).await.is_err() {
                        break;
                    }
                    let _ = s.flush().await;
                }
            });
            let mut client = TcpStream::connect(addr).await.unwrap();
            assert!(add_client(&mut client, "*7*300#1#2#3#4#40000#1*##").await.is_err());
            server.await.unwrap();
        });
    }

    #[test]
    fn read_until_ack_or_nack_reassembles_a_fragmented_ack() {
        // The shared helper (used by BOTH the monitor handshake and add_client) must reassemble an
        // ACK split across reads and report the position via the accumulator — this covers the
        // monitor-ACK fragmentation path that has no socket-level test of its own. Only the server
        // side writes here; the client reads via the helper, so just AsyncWriteExt is needed.
        use tokio::io::AsyncWriteExt;
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
            let addr = listener.local_addr().unwrap();
            let server = tokio::spawn(async move {
                let (mut s, _) = listener.accept().await.unwrap();
                // A pre-ACK banner, then the ACK split across writes, then a trailing bus frame.
                s.write_all(b"junk*").await.unwrap();
                s.flush().await.unwrap();
                s.write_all(b"#*1##*7*300#127#0#0#1#5002#1*##").await.unwrap();
                s.flush().await.unwrap();
            });
            let mut client = TcpStream::connect(addr).await.unwrap();
            let mut acc = Vec::new();
            assert!(read_until_ack_or_nack(&mut client, &mut acc).await.unwrap());
            // The ACK is located within the accumulator, so a caller can frame the bytes past it.
            let pos = find_sub(&acc, AV_ACK).unwrap();
            assert!(acc[pos + AV_ACK.len()..].starts_with(b"*7*300#127#0#0#1#"));
            server.await.unwrap();
        });
    }

    #[test]
    fn read_until_ack_or_nack_caps_a_flood_of_non_control_bytes() {
        // A peer streaming non-control bytes must not grow the buffer unboundedly: past
        // MAX_CTRL_BYTES the helper errors (which makes the monitor reconnect / the arm fail).
        use tokio::io::AsyncWriteExt;
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
            let addr = listener.local_addr().unwrap();
            let server = tokio::spawn(async move {
                let (mut s, _) = listener.accept().await.unwrap();
                // Well over the cap, and never a control frame.
                let flood = vec![b'x'; MAX_CTRL_BYTES + 1024];
                let _ = s.write_all(&flood).await;
                let _ = s.flush().await;
            });
            let mut client = TcpStream::connect(addr).await.unwrap();
            let mut acc = Vec::new();
            let err = read_until_ack_or_nack(&mut client, &mut acc).await.unwrap_err();
            assert_eq!(err.kind(), std::io::ErrorKind::InvalidData);
            // The server writes are already best-effort (the client drops after the cap), so unwrap
            // the JoinHandle to surface a genuine server-task panic rather than swallowing it.
            server.await.unwrap();
        });
    }

    #[test]
    fn read_until_ack_or_nack_honours_byte_order_when_both_frames_arrive() {
        // The panel sends exactly one reply, but if a misbehaving peer ever put both a NACK and
        // an ACK in one buffer, the outcome must follow byte order (the FIRST frame wins) rather
        // than letting a trailing ACK override an earlier refusal. Cover both orderings.
        use tokio::io::AsyncWriteExt;
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            async fn outcome(payload: &'static [u8]) -> bool {
                let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
                let addr = listener.local_addr().unwrap();
                let server = tokio::spawn(async move {
                    let (mut s, _) = listener.accept().await.unwrap();
                    s.write_all(payload).await.unwrap();
                    s.flush().await.unwrap();
                });
                let mut client = TcpStream::connect(addr).await.unwrap();
                let mut acc = Vec::new();
                let got = read_until_ack_or_nack(&mut client, &mut acc).await.unwrap();
                server.await.unwrap();
                got
            }
            // NACK before ACK ⇒ refusal wins (false); ACK before NACK ⇒ success (true).
            assert!(!outcome(b"*#*0##*#*1##").await);
            assert!(outcome(b"*#*1##*#*0##").await);
        });
    }

    #[test]
    fn arm_rejects_equal_video_and_audio_ports() {
        // Equal ports would collide two RTP streams on one UDP port; arm() must fail fast BEFORE
        // touching :30007 (the guard returns before resolve/connect, so no socket is needed).
        use std::collections::HashMap;
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            let mut m = HashMap::new();
            m.insert("MQTT_HOST".to_string(), "h".to_string());
            m.insert("CAMERA_TARGET_HOST".to_string(), "127.0.0.1".to_string());
            m.insert("CAMERA_VIDEO_PORT".to_string(), "5000".to_string());
            m.insert("CAMERA_AUDIO_PORT".to_string(), "5000".to_string());
            let cfg = Arc::new(crate::config::Config::from_map(m));
            let err = arm(&cfg).await.unwrap_err();
            assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput);
        });
    }

    #[test]
    fn arm_rejects_an_unroutable_target() {
        // A loopback target collides with DEVICE_MEDIA_PREFIX (`*7*300#127#0#0#1#…`), and 0.0.0.0
        // is a bind wildcard, not a routable host; arm() must reject both after resolution, before
        // connecting (default ports 40000/40002 are distinct and non-zero, so we reach the check).
        // 127.0.0.2 is ALSO rejected here: the loopback carve-out applies only in on-device mode,
        // and these configs leave CAMERA_ONDEVICE unset (off-device), so it stays unroutable.
        use std::collections::HashMap;
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        rt.block_on(async {
            for target in ["127.0.0.1", "0.0.0.0", "127.0.0.2"] {
                let mut m = HashMap::new();
                m.insert("MQTT_HOST".to_string(), "h".to_string());
                m.insert("CAMERA_TARGET_HOST".to_string(), target.to_string());
                let cfg = Arc::new(crate::config::Config::from_map(m));
                assert!(!cfg.camera_ondevice, "target {target}");
                let err = arm(&cfg).await.unwrap_err();
                assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput, "target {target}");
            }
        });
    }

    #[test]
    fn check_camera_target_carves_out_only_the_ondevice_alias() {
        // Pure validation — no socket, so this is hermetic even if `bt_av_media` happens to be
        // listening on :30007 (the flaw in an arm()-based acceptance test: it would connect, and
        // could return Ok / mutate a running daemon). `arm()` calls this exact helper.
        let ok = |ip: &str, ondevice| check_camera_target(ip.parse().unwrap(), ondevice).is_ok();
        // On-device mode accepts EXACTLY the loopback alias 127.0.0.2 (go2rtc listens there)…
        assert!(ok("127.0.0.2", true));
        // …but the carve-out is a single address, NOT a blanket loopback allow: 127.0.0.1 (the
        // DEVICE_MEDIA_PREFIX collision) and 0.0.0.0 (bind wildcard) stay rejected on-device.
        assert!(!ok("127.0.0.1", true));
        assert!(!ok("0.0.0.0", true));
        // Off-device, even 127.0.0.2 is rejected — the carve-out applies only in on-device mode.
        assert!(!ok("127.0.0.2", false));
        assert!(!ok("127.0.0.1", false));
        assert!(!ok("0.0.0.0", false));
        // A routable host is accepted in either mode.
        assert!(ok("192.168.1.50", false));
        assert!(ok("192.168.1.50", true));
        // A rejection surfaces as InvalidInput — the kind arm() propagates to its caller.
        let err = check_camera_target("127.0.0.1".parse().unwrap(), false).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::InvalidInput);
        // The message is mode-specific: on-device rejections name the one permitted address
        // (127.0.0.2) rather than the misleading blanket "no loopback" wording.
        let ondevice_err = check_camera_target("127.0.0.1".parse().unwrap(), true).unwrap_err();
        assert!(ondevice_err.to_string().contains("127.0.0.2"));
        assert!(!err.to_string().contains("127.0.0.2"));
    }

    #[test]
    fn resolve_ipv4_accepts_literal() {
        // A literal dotted IPv4 resolves synchronously (no DNS). enable_all() so the DNS path's
        // bounded `tokio::time::timeout` has a time driver for the empty-target case below.
        let rt = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
        let v4 = rt.block_on(resolve_ipv4("192.168.1.50"));
        assert_eq!(v4, Some(Ipv4Addr::new(192, 168, 1, 50)));
        // An empty target yields nothing rather than a bogus address (the lookup errors, bounded).
        assert_eq!(rt.block_on(resolve_ipv4("")), None);
    }

    // --- camera-live signal file + filler→live cutover (issue #180) ---

    #[test]
    fn cutover_inputs_are_the_runtime_sdp_and_the_filler_clip() {
        // The cutover respawn must be able to identify BOTH the live producer (reading the runtime SDP)
        // and the filler producer (reading loading.mp4) — whichever is running when the siphon arms — so
        // its input set is exactly those two, and the paths match their single sources of truth.
        assert_eq!(PRODUCER_INPUTS, &[crate::sprop::SDP_PATH, LOADING_CLIP_PATH]);
        // The FILLER-only set is exactly the loading clip: the retry SIGTERMs with it (so it can't churn the
        // live SDP producer) and the completion re-scan uses it to confirm no filler remains.
        assert_eq!(FILLER_INPUTS, &[LOADING_CLIP_PATH]);
        // The LIVE-only set is exactly the runtime SDP: the session-EXIT cutover SIGTERMs with it so a bare
        // monitor drop cuts a silent live feed to the filler without needlessly restarting a cold filler.
        assert_eq!(LIVE_INPUTS, &[crate::sprop::SDP_PATH]);
        assert_eq!(crate::sprop::SDP_PATH, "/var/run/btmqttd/doorbell.sdp");
        assert_eq!(LOADING_CLIP_PATH, "/etc/btmqttd/go2rtc/loading.mp4");
        // The signal path lives on tmpfs (cleared every boot ⇒ defaults to "not live") and must match the
        // `SIG=` the generated wrapper checks.
        assert_eq!(CAMERA_LIVE_SIGNAL_PATH, "/var/run/btmqttd/camera-live");
    }

    #[tokio::test]
    async fn set_then_clear_signal_toggles_the_marker() {
        // set_signal_at creates the marker (existence is the whole signal); clear_signal_at removes it;
        // a second clear on the now-absent marker is SUCCESS (the common per-session-backstop case), never
        // an error to log. Exercised on a temp path so it never touches the fixed tmpfs location.
        let dir = std::env::temp_dir().join(format!("btmqttd-camlive-{}", std::process::id()));
        let path = dir.join("camera-live").to_string_lossy().into_owned();

        set_signal_at(&path).await.unwrap();
        assert!(tokio::fs::try_exists(&path).await.unwrap(), "marker exists after set");

        clear_signal_at(&path).await.unwrap();
        assert!(!tokio::fs::try_exists(&path).await.unwrap(), "marker gone after clear");

        // Clearing an already-absent marker succeeds (NotFound is treated as done).
        clear_signal_at(&path).await.unwrap();

        let _ = tokio::fs::remove_dir_all(&dir).await;
    }

    #[tokio::test]
    async fn clear_reports_absent_and_gates_respawn_off_device() {
        // The removal now REPORTS whether the marker is confirmed ABSENT so callers can GATE the producer
        // respawn on it (issue #180): a lost removal must not respawn, or the wrapper would re-read the stale
        // marker and serve the silent live SDP. Off-device there is no marker/filler, so the clear is
        // trivially "absent" → true, and `clear_and_respawn_to_filler` returns true having skipped the
        // respawn. (The on-device removal + its retry write the FIXED tmpfs path, covered by the
        // clear_signal_at temp-file test and integration.)
        use std::collections::HashMap;
        let mut m = HashMap::new();
        m.insert("MQTT_HOST".to_string(), "h".to_string());
        let cfg = Arc::new(crate::config::Config::from_map(m));
        assert!(!cfg.camera_ondevice);
        assert!(clear_camera_live_signal(&cfg).await, "off-device: marker trivially absent → true");
        assert!(
            clear_and_respawn_to_filler(&cfg, LIVE_INPUTS, "test: off-device clear+respawn is a no-op").await,
            "off-device: clears (true) and skips the respawn"
        );
    }

    #[tokio::test]
    async fn set_camera_live_signal_is_a_noop_off_device() {
        // Finding #2 (#180): the cutover respawn is GATED on the marker write succeeding, so
        // set_camera_live_signal must report whether the marker now exists. Off-device there is no
        // on-device producer/filler, so it creates nothing and returns `false` — and the arm branch then
        // skips the respawn (a no-op off-device anyway) instead of SIGTERMing a producer with no marker
        // present. (The on-device create→`true` mapping is the trivial Ok arm over the temp-file-tested
        // set_signal_at; it writes the FIXED tmpfs path, so it is not exercised against /var/run here.)
        use std::collections::HashMap;
        let mut m = HashMap::new();
        m.insert("MQTT_HOST".to_string(), "h".to_string());
        let cfg = Arc::new(crate::config::Config::from_map(m));
        assert!(!cfg.camera_ondevice);
        assert!(!set_camera_live_signal(&cfg).await, "off-device: nothing created, so no respawn is gated in");
    }

    #[tokio::test]
    async fn cut_over_to_live_is_a_noop_off_device() {
        // Finding A (#180): `cut_over_to_live` is the shared "marker-then-gated-respawn" step used by BOTH
        // the arm branch and the per-iteration retry. Off-device set_camera_live_signal returns false, so
        // the helper returns false WITHOUT touching the producer — the arm branch then records
        // live_marked=false and the retry never spins (there is nothing to mark live off-device). (The
        // on-device true path SIGTERMs a live /proc scan against the fixed daemon path, so it is covered by
        // the integration behaviour rather than exercised against /proc here.)
        use std::collections::HashMap;
        let mut m = HashMap::new();
        m.insert("MQTT_HOST".to_string(), "h".to_string());
        let cfg = Arc::new(crate::config::Config::from_map(m));
        assert!(!cfg.camera_ondevice);
        assert!(
            !cut_over_to_live(&cfg, PRODUCER_INPUTS, "test: off-device cutover is a no-op", true).await,
            "off-device: no marker, so the cutover reports not-live (without touching a producer or the readiness file) and won't spin"
        );
    }

    #[tokio::test]
    async fn set_signal_at_creates_a_missing_parent_dir() {
        // go2rtcd assembles /var/run/btmqttd at boot, but arm() must still be able to signal if the dir
        // is momentarily absent (a race, or a manual go2rtc start) — so set_signal_at makes the parent.
        let base = std::env::temp_dir().join(format!("btmqttd-camlive-parent-{}", std::process::id()));
        let _ = tokio::fs::remove_dir_all(&base).await; // ensure the parent does NOT exist yet
        let path = base.join("nested").join("camera-live").to_string_lossy().into_owned();

        set_signal_at(&path).await.unwrap();
        assert!(tokio::fs::try_exists(&path).await.unwrap(), "marker created under a fresh parent dir");

        let _ = tokio::fs::remove_dir_all(&base).await;
    }
}
